name: CI

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Build Olive (CentOS 7)
    runs-on: ubuntu-latest
    container:
      image: simranb/olive-ci-centos
    steps:
      - uses: actions/checkout@v2
        with:
          repository: olive-editor/olive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja"

      - name: Build
        # TODO: Be explicit about dir? Is this persistent between steps?
        # working-directory: ${{ github.workspace }}/build
        working-directory: build
        # HACK: Comment out -Wshadow build flag which turns shadow warnings into errors
        run: |
          sed -i -e "s/ -Wshadow/#-Wshadow/" ../app/CMakeLists.txt
          cmake --build .

      - name: Install
        working-directory: build
        run: |
          cmake --install app --prefix appdir/usr

      - name: Bundle
        working-directory: build
        env:
          ARCH: x86_64
          LD_LIBRARY_PATH: "\
            /usr/local/lib64:\
            /usr/local/lib/python3.7/site-packages/numpy/.libs:\
            /usr/lib64/pulseaudio:\
            $LD_LIBRARY_PATH"
        run: >
          /usr/local/linuxdeployqt-x86_64.AppImage
          appdir/usr/share/applications/org.olivevideoeditor.Olive.desktop
          -appimage
          --appimage-extract-and-run

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: olive-appimage
          path: build/Olive*-x86_64.AppImage
