name: Fake time
on: push
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - run: |
          Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Parameters -Name "Type"
          Set-Date -Adjust (New-TimeSpan -Days 20)
          [Threading.Thread]::Sleep($(New-TimeSpan -Minutes 20))
          Get-Date
