name: Issue Test

on:
  issue_comment:

jobs:
  issue-commented:
    name: Issue commented
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Event (env)
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
      - name: GitHub Event (cat, no substitution)
        run: |
          cat<<'EOF'
            ${{ toJSON(github.event) }}
          EOF
      - name: GitHub Event (cat, with substitution)
        run: |
          cat<<EOF
            ${{ toJSON(github.event) }}
          EOF
