name: Issue Test

on:
  issue_comment:

jobs:
  issue-commented:
    name: Issue commented
    runs-on: ubuntu-latest
    steps:
      - name: Default env vars
        run: |
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_SHA = $GITHUB_SHA"
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
      - name: GitHub Event (env)
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
      - name: GitHub Event (cat, no substitution)
        run: |
          cat<<'EOF'
            ${{ toJSON(github.event) }}
          EOF
      - name: GitHub Event (cat, with substitution)
        run: |
          cat<<EOF
            ${{ toJSON(github.event) }}
          EOF
