name: Local Actions

on:
  push:
    branches:
      - master

jobs:
  subfolder-action:
    name: Subfolder Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        #uses: ./.github/actions/checkout
      - name: Use local action
        id: result
        uses: ./.github/actions/local
        with:
          value: Howdy there
      - name: Output
        run: |
          echo '${{ steps.result.outputs.lower }}'
          echo '${{ steps.result.outputs.upper }}'
  submodule-action:
    name: Git Submodule Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        #uses: ./.github/actions/checkout
        with:
          submodules: recursive
      - name: Use submodule action
        id: result
        uses: ./.github/actions/submodule
        with:
          string: Howdy there
      - name: Output
        run: |
          echo '${{ steps.result.outputs.reversed }}'
          echo '${{ steps.result.outputs.repeated }}'
  local-action:
    name: Local Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./.github/actions/checkout
      # Actions in your organization or own account don't need to be added to the allowlist
      - name: Use own Action
        id: result
        uses: Simran-B/github-action
        with:
          string: Howdy there
      - name: Output
        run: |
          echo '${{ steps.result.outputs.reversed }}'
          echo '${{ steps.result.outputs.repeated }}'
