name: Local Actions

on:
  push:
    branches:
      - master_DISABLED

jobs:
  subfolder-action:
    name: Subfolder Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        #uses: actions/checkout@v2
        #uses: ./.github/actions/checkout
        uses: Simran-B/checkout@v2
      - name: Use local action
        id: result
        uses: ./.github/actions/local
        with:
          value: Howdy there
          secret: ${{ secrets.LEAK_ME }}
      - name: Output
        run: |
          echo 'lower: ${{ steps.result.outputs.lower }}'
          echo 'upper: ${{ steps.result.outputs.upper }}'
          echo 'leak: ${{ steps.result.outputs.leak }}' (on purpose)
  submodule-action:
    name: Git Submodule Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        #uses: actions/checkout@v2
        #uses: ./.github/actions/checkout
        uses: Simran-B/checkout@v2
        with:
          submodules: recursive
      - name: Use submodule action
        id: result
        uses: ./.github/actions/submodule
        with:
          string: Howdy there
      - name: Output
        run: |
          echo '${{ steps.result.outputs.reversed }}'
          echo '${{ steps.result.outputs.repeated }}'
  local-action:
    name: Local Action
    runs-on: ubuntu-latest
    steps:
    # - name: Fetch checkout action
    #   continue-on-error: true
    #   run: |
    #     mkdir -p temp/checkout/dist
    #     cd temp/checkout
    #     curl -sSO https://raw.githubusercontent.com/Simran-B/olive-ci/master/.github/actions/checkout/action.yml
    #     cd dist
    #     curl -sSO https://raw.githubusercontent.com/Simran-B/olive-ci/master/.github/actions/checkout/dist/index.js
    #     curl -sSO https://raw.githubusercontent.com/Simran-B/olive-ci/master/.github/actions/checkout/dist/problem-matcher.json
    #     pwd
    #     find ..
      - name: Checkout repository
        #uses: ./temp/checkout
        uses: actions/checkout@v2
      # Actions in your organization or own account don't need to be added to the allowlist
      - name: Use own Action
        id: result
        uses: Simran-B/github-action@main
        with:
          string: Howdy there
      - name: Output
        run: |
          echo '${{ steps.result.outputs.reversed }}'
          echo '${{ steps.result.outputs.repeated }}'
