# If name is omitted, then the path to file is used, e.g.
# .github/workflows/test-windows.yaml
name: Windows Test

on:
  push:
    branches:
      - windows-test

defaults:
  run:
    # Windows default is powershell!
    shell: cmd

jobs:
  set-env:
    name: set-env test
    runs-on: windows-latest
    steps:
      - name: with quotes
        run: |
          echo "::set-env name=pkgname1::Olive hash = %GITHUB_SHA:~0,8%"

      - name: without quotes
        run: |
          echo ::set-env name=pkgname2::Olive hash = %GITHUB_SHA:~0,8%

      - name: print
        run: |
          echo PKGNAME1 = %PKGNAME1% ^| JSON: ${{ toJSON( env.PKGNAME1 ) }}
          echo PKGNAME2 = %PKGNAME2% ^| JSON: ${{ toJSON( env.PKGNAME2 ) }}

  find-nsis:
    name: Find NSIS
    runs-on: windows-latest
    steps:
      - name: Already in PATH?
        run: |
          where makensis
      # BROKEN: ${{ env.PATH }} results in empty string,
      # i.e. PATH is mostly cleared and thus where command cannot be found anymore
      #- name: Pass env (action syntax)
      #  env:
      #    PATH: C:\Program Files (x86)\NSIS;${{ env.PATH }}
      #  run: |
      #    echo %PATH%
      #    where makensis

      # BROKEN: %PATH% isn't resolved either
      #- name: Pass env (shell syntax)
      #  env:
      #    PATH: C:\Program Files (x86)\NSIS;%PATH%
      #  run: |
      #      echo %PATH%
      #      where makensis
      - name: Set env (shell)
        run: |
          md new_location
          copy "C:\Program Files (x86)\NSIS\makensis.exe" new_location
          set PATH=%CD%\new_location;%PATH%
          echo %PATH%
          where makensis
      - name: Set env (action)
        run: |
          md another_location
          copy "C:\Program Files (x86)\NSIS\makensis.exe" another_location
          echo ::set-env name=PATH::%CD%\another_location;%PATH%
      # set-env changes only visible to subsequent steps!
      - name: Updated?
        run: |
          echo %PATH%
          where makensis

  powershell:
    name: PowerShell test
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Substring
        run: |
          Write-Output "Olive $($env:GITHUB_SHA.substring(0, 8))"
      - name: Set env
        run: |
          New-Item other_location -ItemType Directory
          Copy-Item "C:\Program Files (x86)\NSIS\makensis.exe" other_location
          Write-Output "::set-env name=PATH::$(Join-Path $(Get-Location) other_location);$env:PATH"
      - name: Updated?
        run: |
          Write-Output $env:PATH
          (Get-Command makensis).Path
      - name: Remove alias (PowerShell < 6)
        run: |
          Remove-Item Alias:curl
          curl --version
      - name: Persistent?
        continue-on-error: true
        run: |
          curl --version
      - name: Remove alias (PowerShell >= 6)
        id: remove-alias-ps6
        continue-on-error: true
        run: |
          Remove-Alias curl
          curl --version
          Write-Host "::set-output name=success::true"
          Write-Host "::set-output name=exists::"
      - name: Type check
        run: |
          Write-Host success boolean? ${{ steps.remove-alias-ps6.outputs.success == true }}
          Write-Host success string? ${{ steps.remove-alias-ps6.outputs.success == 'true' }}
          Write-Host success JSON: ${{ toJSON(steps.remove-alias-ps6.outputs.success) }}
          Write-Host
          Write-Host exists null? ${{ steps.remove-alias-ps6.outputs.exists == null }}
          Write-Host exists boolean? ${{ steps.remove-alias-ps6.outputs.exists == true }}
          Write-Host exists string? ${{ steps.remove-alias-ps6.outputs.exists == '' }}
          Write-Host exists JSON: ${{ toJSON(steps.remove-alias-ps6.outputs.exists) }}
      - name: Persistent?
        continue-on-error: true
        run: |
          curl --version
        if: steps.remove-alias-ps6.outputs.success
