name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      trigger:
        description: Trigger Name
        required: true
        default: manual

jobs:
  pre-build:
    name: Init matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [0, 1, 2]
    steps: []
    outputs:
      build: ${{ matrix.build }}
      event_name: ${{ github.event_name }}
  build:
    name: Test Workflow
    runs-on: ubuntu-latest
    needs: [pre-build]
    strategy:
      matrix:
        build: [0, 1, 2]
        include:
          - build: 0
            cause: ${{ github.event.inputs.trigger }}
          - build: 1
            cause: automatic
          - build: 2
            cause: automatic
    if: >-
      (needs.pre-build.event_name == 'workflow_dispatch' && needs.pre-build.build == 0) ||
      (needs.pre-build.event_name != 'workflow_dispatch' && needs.pre-build.build != 0)
    steps:
      - name: Manual inputs
        env:
          VERSION: '1.2.3'
          PREFIX: '# 1'
        run: |
          echo "trigger: ${{ github.event.inputs.trigger }}"
          echo "build: ${{ matrix.build }}, cause: ${{ matrix.cause }}"
          echo "OR: ${{ github.event.inputs.trigger || matrix.cause }}"
          echo "OR: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trigger || matrix.cause }}"
          echo "OR falsey: ${{ 0 || 'truthy' }} / ${{ '' || 'truthy' }} / ${{ false || 'truthy' }} / ${{ null || 'truthy' }} / ${{ ' ' || 'space?' }}"
          echo "fake ternary: ${{ 0 == 0 && 'first' || 'second' }} / ${{ 0 != 0 && 'first' || 'second' }} / ${{ 0 == 0 && false || 'second' }}"
          echo "startsWith: ${{ startsWith(format('# {0}', env.VERSION), env.PREFIX) }}"
          echo "cast to string:"
          cat << "EOF"
            ${{ toJSON('quoted?') }}
          EOF
          cat << "EOF"
            ${{ toJSON('foo' == 'foo') }}
          EOF
          cat << "EOF"
            ${{ toJSON(format('foo' == 'foo')) }}
          EOF
          echo
          echo "github context:"
          cat << "EOF"
            ${{ toJSON(github) }}
          EOF
      - name: Only if manually triggered
        run: |
          echo "This workflow run was triggered manually"
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - name: Only on push to branch
        run: |
          echo "This workflow run was triggered automatically"
        if: ${{ github.event_name != 'workflow_dispatch' }}
