name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      trigger:
        description: Trigger Name
        required: true
        default: manual

jobs:
  create-matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix-manual.outputs.matrix || steps.set-matrix-automatic.outputs.matrix }}
    steps:
      - name: Set Matrix (manual)
        id: set-matrix-manual
        env:
          MATRIX_JSON: '
            { "include": [{
              "build": 1,
              "cause": ${{ toJSON(github.event.inputs.trigger) }}
            }]}'
        run: echo "::set-output name=matrix::$MATRIX_JSON"
        if: github.event_name == 'workflow_dispatch'
      - name: Set Matrix (automatic)
        id: set-matrix-automatic
        env:
          MATRIX_JSON: '
            { "include": [{
              "build": 1,
              "cause": "automatic"
            },{
              "build": 2,
              "cause": "automatic"
            }]}'
        run: echo "::set-output name=matrix::$MATRIX_JSON"
        if: github.event_name != 'workflow_dispatch'
  build:
    name: Test Workflow
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
      # build: [0, 1, 2]
      # include:
      #   - build: 0
      #     cause: ${{ github.event.inputs.trigger }}
      #   - build: 1
      #     cause: automatic
      #   - build: 2
      #     cause: automatic
    steps:
      - name: Inputs
        env:
          VERSION: '1.2.3'
          PREFIX: '# 1'
        run: |
          echo "trigger = ${{ github.event.inputs.trigger }} (workflow_dispatch only)"
          echo "build = ${{ matrix.build }}"
          echo "cause = ${{ matrix.cause }}"
          echo "trigger OR cause = ${{ github.event.inputs.trigger || matrix.cause }}"
          echo "workflow_dispatch ? trigger : cause = ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trigger || matrix.cause }}"
          echo "OR falsey: ${{ 0 || 'truthy' }} / ${{ '' || 'truthy' }} / ${{ false || 'truthy' }} / ${{ null || 'truthy' }} / ${{ ' ' || 'space?' }}"
          echo "pseudo ternary: ${{ 0 == 0 && 'first' || 'second' }} / ${{ 0 != 0 && 'first' || 'second' }} / ${{ 0 == 0 && false || 'second' }}"
          echo "startsWith: ${{ startsWith(format('# {0}', env.VERSION), env.PREFIX) }}"
          echo "cast to string:"
          cat<<'EOF'
            ${{ toJSON('quoted?') }}
          EOF
          cat<<'EOF'
            ${{ toJSON('foo' == 'foo') }}
          EOF
          cat<<'EOF'
            ${{ toJSON(format('foo' == 'foo')) }}
          EOF
          echo
          echo "github context:"
          cat<<'EOF'
            ${{ toJSON(github) }}
          EOF
      - name: Only if manually triggered
        run: |
          echo "This workflow run was triggered manually"
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - name: Only on push to branch
        run: |
          echo "This workflow run was triggered automatically"
        if: ${{ github.event_name != 'workflow_dispatch' }}
